$background-darker = rgb(1e2326)
$background = rgb(272e33)
$selection = rgb(7a8478)
$foreground = rgb(d3c6aa)
$comment = rgb(859289)
$green = rgb(a7c080)
$blue = rgb(7fbbb3)
$aqua = rgb(83c092)
$orange = rgb(e69875)
$purple = rgb(d699b6)
$red = rgb(e67e80)
$yellow = rgb(dbbc7f)
